import type { Product, Bundle } from '../types';

export const createDemoData = (): { products: Product[], bundles: Bundle[] } => {
  const images = {
    laptops: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop'],
    cameras: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop'],
    monitors: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop'],
    audio: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&auto=format&fit=crop'],
    clothing: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop'],
    setup: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1600508774634-4e11d34730e2?w=800&auto=format&fit=crop'],
  };

  const idCounter = { current: 1000 };
  const getNextId = () => (idCounter.current++).toString();
  const getPastDate = (daysAgo: number) => {
    const d = new Date();
    d.setDate(d.getDate() - daysAgo);
    return d.toISOString();
  };

  const dummyProducts: Product[] = [
    {
      id: getNextId(),
      name: 'MacBook Pro 16" M3 Max',
      shop: 'Apple Store',
      url: 'https://apple.com',
      mainCat: 'Hardware',
      subCats: ['Laptops'],
      price: 3999,
      discount: 0,
      finalPrice: 3999,
      rating: 5,
      details: 'Das ultimative Setup-Upgrade für Video-Editing und Coding.',
      imgs: [images.laptops[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(45),
      isFavorite: true,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Sony A7 IV Vollformat-Kamera',
      shop: 'Calumet',
      url: 'https://calumetphoto.de',
      mainCat: 'Hardware',
      subCats: ['Kameras'],
      price: 2799,
      discount: 10,
      finalPrice: 2519.1,
      rating: 4.8,
      details: 'Perfekter Hybrid für Foto und Video.',
      imgs: [images.cameras[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(12),
      isFavorite: true,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'LG 38" Ultrawide Monitor',
      shop: 'Amazon',
      url: 'https://amazon.de',
      mainCat: 'Hardware',
      subCats: ['Monitore', 'Gaming'],
      price: 1200,
      discount: 25,
      finalPrice: 900,
      rating: 4.5,
      details: 'Mehr Platz für Timeline und Code.',
      imgs: [images.monitors[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(5),
      isFavorite: false,
      status: 'reduced'
    },
    {
      id: getNextId(),
      name: 'Shure SM7B Mikrofon',
      shop: 'Thomann',
      url: 'https://thomann.de',
      mainCat: 'Setup',
      subCats: ['Audio', 'Mikrofone'],
      price: 389,
      discount: 0,
      finalPrice: 389,
      rating: 4.9,
      details: 'Podcast und Voice-Over Standard.',
      imgs: [images.audio[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(60),
      isFavorite: true,
      status: 'bought'
    },
    {
      id: getNextId(),
      name: 'Ergonomischer Bürostuhl',
      shop: 'Herman Miller',
      url: 'https://hermanmiller.com',
      mainCat: 'Setup',
      subCats: ['Stühle'],
      price: 1450,
      discount: 0,
      finalPrice: 1450,
      rating: 4.7,
      details: 'Rückenfreundlich für lange Sessions.',
      imgs: [images.setup[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(20),
      isFavorite: false,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Sony WH-1000XM5',
      shop: 'MediaMarkt',
      url: 'https://mediamarkt.de',
      mainCat: 'Hardware',
      subCats: ['Audio'],
      price: 329,
      discount: 15,
      finalPrice: 279.65,
      rating: 4.6,
      details: 'ANC Kopfhörer für unterwegs.',
      imgs: [images.audio[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(2),
      isFavorite: true,
      status: 'reduced'
    },
    {
      id: getNextId(),
      name: 'Minimalistischer Hoodie',
      shop: 'Uniqlo',
      url: 'https://uniqlo.com',
      mainCat: 'Clothing',
      subCats: ['Jacken'],
      price: 49.90,
      discount: 0,
      finalPrice: 49.90,
      rating: 4.2,
      details: 'Bequem für Homeoffice.',
      imgs: [images.clothing[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(10),
      isFavorite: false,
      status: 'bought'
    },
    {
      id: getNextId(),
      name: 'Smart Lights',
      shop: 'Philips Hue',
      url: 'https://philips-hue.com',
      mainCat: 'Setup',
      subCats: ['Beleuchtung', 'Deko'],
      price: 149,
      discount: 5,
      finalPrice: 141.55,
      rating: 4.3,
      details: 'Ambiente für das Studio-Setup.',
      imgs: [images.setup[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(30),
      isFavorite: false,
      status: 'active'
    },
    // Adding more products to reach 20 total
    {
      id: getNextId(),
      name: 'Keychron Q1 Pro',
      shop: 'Keychron',
      url: 'https://keychron.com',
      mainCat: 'Hardware',
      subCats: ['Tastaturen'],
      price: 219,
      discount: 0,
      finalPrice: 219,
      rating: 4.8,
      details: 'Kabellose mechanische Custom-Tastatur.',
      imgs: [images.laptops[1]], // using laptop placeholder
      mainImgIdx: 0,
      dateAdded: getPastDate(8),
      isFavorite: true,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Logitech MX Master 3S',
      shop: 'Amazon',
      url: 'https://amazon.de',
      mainCat: 'Hardware',
      subCats: ['Mäuse'],
      price: 129,
      discount: 15,
      finalPrice: 109.65,
      rating: 4.9,
      details: 'Der Standard für Produktivität.',
      imgs: [images.laptops[0]], // placeholder
      mainImgIdx: 0,
      dateAdded: getPastDate(3),
      isFavorite: true,
      status: 'bought'
    },
    {
      id: getNextId(),
      name: 'Schreibtischlampe',
      shop: 'BenQ',
      url: 'https://benq.com',
      mainCat: 'Setup',
      subCats: ['Beleuchtung'],
      price: 159,
      discount: 0,
      finalPrice: 159,
      rating: 4.5,
      details: 'Augenschonendes Licht für den Bildschirmarbeitsplatz.',
      imgs: [images.setup[0]], // placeholder
      mainImgIdx: 0,
      dateAdded: getPastDate(14),
      isFavorite: false,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Sony FE 35mm f/1.4 GM',
      shop: 'Calumet',
      url: 'https://calumetphoto.de',
      mainCat: 'Hardware',
      subCats: ['Kameras'],
      price: 1699,
      discount: 0,
      finalPrice: 1699,
      rating: 4.9,
      details: 'Unglaubliche Schärfe und Bokeh.',
      imgs: [images.cameras[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(25),
      isFavorite: true,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Elgato Stream Deck MK.2',
      shop: 'Corsair',
      url: 'https://elgato.com',
      mainCat: 'Hardware',
      subCats: ['Gadgets'],
      price: 149,
      discount: 10,
      finalPrice: 134.1,
      rating: 4.7,
      details: 'Makros und Shortcuts auf Knopfdruck.',
      imgs: [images.setup[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(2),
      isFavorite: false,
      status: 'reduced'
    },
    {
      id: getNextId(),
      name: 'Peak Design Everyday Backpack',
      shop: 'Peak Design',
      url: 'https://peakdesign.com',
      mainCat: 'Clothing',
      subCats: ['Bags'],
      price: 299,
      discount: 0,
      finalPrice: 299,
      rating: 4.8,
      details: 'Der beste Kamerarucksack.',
      imgs: [images.clothing[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(35),
      isFavorite: true,
      status: 'bought'
    },
    {
      id: getNextId(),
      name: 'Rode PodMic',
      shop: 'Thomann',
      url: 'https://thomann.de',
      mainCat: 'Setup',
      subCats: ['Mikrofone', 'Audio'],
      price: 109,
      discount: 0,
      finalPrice: 109,
      rating: 4.6,
      details: 'Dynamisches Mikrofon im Einstiegsbereich.',
      imgs: [images.audio[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(50),
      isFavorite: false,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Figma Pro Abo (Jährlich)',
      shop: 'Figma',
      url: 'https://figma.com',
      mainCat: 'Software',
      subCats: ['Design'],
      price: 144,
      discount: 0,
      finalPrice: 144,
      rating: 5.0,
      details: 'Design Tooling.',
      imgs: [images.laptops[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(120),
      isFavorite: true,
      status: 'bought'
    },
    {
      id: getNextId(),
      name: 'Notion Plus Abo',
      shop: 'Notion',
      url: 'https://notion.so',
      mainCat: 'Software',
      subCats: ['Produktivität'],
      price: 96,
      discount: 0,
      finalPrice: 96,
      rating: 4.5,
      details: 'Knowledge Base & Projektmanagement.',
      imgs: [images.monitors[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(200),
      isFavorite: false,
      status: 'bought'
    },
    {
      id: getNextId(),
      name: 'Oversized T-Shirt',
      shop: 'Zara',
      url: 'https://zara.com',
      mainCat: 'Clothing',
      subCats: ['T-Shirts'],
      price: 25.90,
      discount: 20,
      finalPrice: 20.72,
      rating: 4.0,
      details: 'Basic Heavy Cotton Tee.',
      imgs: [images.clothing[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(6),
      isFavorite: false,
      status: 'reduced'
    },
    {
      id: getNextId(),
      name: 'iPad Pro 11"',
      shop: 'Apple',
      url: 'https://apple.com',
      mainCat: 'Hardware',
      subCats: ['Tablets'],
      price: 1049,
      discount: 5,
      finalPrice: 996.55,
      rating: 4.9,
      details: 'Perfekt für Skizzen und unterwegs.',
      imgs: [images.laptops[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(15),
      isFavorite: true,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Sennheiser IE 200',
      shop: 'Sennheiser',
      url: 'https://sennheiser.com',
      mainCat: 'Hardware',
      subCats: ['Audio'],
      price: 149,
      discount: 0,
      finalPrice: 149,
      rating: 4.4,
      details: 'In-Ear Monitore für klaren Sound.',
      imgs: [images.audio[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(18),
      isFavorite: false,
      status: 'active'
    },
    {
      id: getNextId(),
      name: 'Kaffeemaschine Siebträger',
      shop: 'Sage',
      url: 'https://sageappliances.com',
      mainCat: 'Home',
      subCats: ['Küche'],
      price: 699,
      discount: 10,
      finalPrice: 629.1,
      rating: 4.8,
      details: 'Für den perfekten Espresso im Homeoffice.',
      imgs: [images.setup[0]],
      mainImgIdx: 0,
      dateAdded: getPastDate(100),
      isFavorite: true,
      status: 'bought'
    },
    {
      id: getNextId(),
      name: 'Govee LED Strip',
      shop: 'Amazon',
      url: 'https://amazon.de',
      mainCat: 'Setup',
      subCats: ['Beleuchtung', 'Deko'],
      price: 35,
      discount: 0,
      finalPrice: 35,
      rating: 4.2,
      details: 'Hintergrundbeleuchtung für den Monitor.',
      imgs: [images.setup[1]],
      mainImgIdx: 0,
      dateAdded: getPastDate(7),
      isFavorite: false,
      status: 'active'
    }
  ];

  const dummyBundles: Bundle[] = [
    {
      id: getNextId(),
      name: 'Traum-Setup 2026',
      dateAdded: getPastDate(1),
      items: [
        { id: dummyProducts[0].id, qty: 1 },
        { id: dummyProducts[2].id, qty: 1 },
        { id: dummyProducts[3].id, qty: 1 },
        { id: dummyProducts[4].id, qty: 1 }
      ]
    },
    {
      id: getNextId(),
      name: 'Reise-Ausrüstung',
      dateAdded: getPastDate(2),
      items: [
        { id: dummyProducts[1].id, qty: 1 },
        { id: dummyProducts[5].id, qty: 1 },
        { id: dummyProducts[6].id, qty: 2 }
      ]
    }
  ];

  return {
    products: dummyProducts,
    bundles: dummyBundles
  };
};
